<?php
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";
    echo "ODIO XAMPP, QUE ESTUPIDEZ ES MONTAR ESE SERVIDOR DE MIERDA";


    echo "CUALQUIER DÍA QUE LEA ESTO, JAIDER ES UN BOBO HPTA IMBECIL";


?>
